%include "colon.inc"
colon "third word", third_word
db "third word explanation", 0

colon "second word", second_word
db "second word explanation", 0

colon "first word", first_word
db "first word explanation", 0

colon "ten word", ten_word
db "ten word explanation", 0

colon "nine word", nine_word
db "nine word explanation", 0

colon "eight word", eight_word
db "eight word explanation", 0

colon "seven word", seven_word
db "seven word explanation", 0

colon "six word", six_word
db "six word explanation", 0

colon "fife word", fife_word
db "fife word explanation", 0

colon "four word", four_word
db "four word explanation", 0

colon "three word", three_word
db "three word explanation", 0

colon "two word", two_word
db "two word explanation", 0

colon "one word", one_word
db "one word explanation", 0

colon "zero word", zero_word
db "zero word explanation", 0
